name: Build Angular

on:
  push:
    branches:
      - develop
      - master
      - 

  pull_request:
    branches:
      - develop
      - master

  workflow_dispatch:

jobs:
  build-angular:
    name: Build Angular
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Node.js 18.x'
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
        
      - name: 'Print current node version'
        run: node -v
        
      - name: 'Print current npm version'
        run: npm -v

      - name: 'Npm ci'
        run: npm ci
        
      - name: 'Install angular cli 15.2.6'
        run: npm install -g @angular/cli@15.2.6
        
      - name: 'Print current angular cli version'
        run: ng version

      - name: 'Angular build'
        run: ng build

      - name: 'Drop artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'angular-build-${{ matrix.environment }}'
          path: './dist/home-page'